version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      FIRESTORE_EMULATOR_HOST: "emulator:8080"
    depends_on:
      - emulator

  emulator:
    image: mtlynch/firestore-emulator:latest
    container_name: firestore-emulator
    ports:
      - "8080:8080"
    environment:
      FIRESTORE_PROJECT_ID: "smart-sync-5b47d"
